# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - run: mkdir pr
    - run: mkdir main
    - uses: jitterbit/get-changed-files@v1
      id: changes
    - uses: actions/checkout@v2
      with:
        path: pr
    - name: OnlyCanModifyFilesInAllowPath
      id: OnlyCanModifyFilesInAllowPath
      run: node ./pr/workflow_scripts/onlyCanModifyFilesInAllowPath.js ${{ steps.changes.outputs.all }}
    - name: CheckMetadata
      id: CheckMetadata
      run: node ./pr/workflow_scripts/checkMetadata/index.js ${{ steps.changes.outputs.all }}
    - uses: actions/checkout@v2  
      with:
        ref: main
        path: main  
    - name: MotAllowDeleteHalfWidthSpace
      id: MotAllowDeleteHalfWidthSpace
      run: node ./pr/workflow_scripts/notAllowDeleteHalfWidthSpace.js ${{ steps.changes.outputs.all }}
    - name: UpdateDate
      id: UpdateDate
      run: node ./pr/workflow_scripts/updateDate/index.js ${{ steps.changes.outputs.all }}

