# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: jitterbit/get-changed-files@v1
      id: changes
    - run: echo ${{steps.changes.outputs.all}}
    - run: echo ${{github.actor}}
    - uses: actions/checkout@v2  
      with:
        ref: main
    - run: ls
    - run: |
        node ./workflow_scripts/test.js ${{ steps.changes.outputs.all }}
        ::set-output name=sam_test::samtest
           
    - name: test
      id: test
      run: node ./workflow_scripts/updateDate/index.js
    - run: echo 'sam test'
    - run: echo ${{steps.test.outputs}}
    - run: echo ${{steps.test.outputs.sam_test}}
    - run: node ./workflow_scripts/checkMetadata/index.js


